// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/library-screen/CommandCenter.tsx": () => import("../components/mockups/library-screen/CommandCenter.tsx"),
  "./components/mockups/library-screen/Conversational.tsx": () => import("../components/mockups/library-screen/Conversational.tsx"),
  "./components/mockups/library-screen/GhostGrid.tsx": () => import("../components/mockups/library-screen/GhostGrid.tsx"),
  "./components/mockups/library-screen/GuidedOnboarding.tsx": () => import("../components/mockups/library-screen/GuidedOnboarding.tsx")
};
